name: pv_forecast
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  nb_utils: ^7.0.9

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Poppins-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
